# Generated by Django 4.1.5 on 2023-03-04 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0002_remove_manager_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='img')),
                ('address', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=20)),
                ('managerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
        ),
    ]
