# Generated by Django 4.1.5 on 2023-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='stress',
            field=models.BooleanField(default='False'),
        ),
    ]
