# Generated by Django 4.1.5 on 2023-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employees_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='msg',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
