# Generated by Django 4.1.5 on 2023-04-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employees_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='confirm',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='employees',
            name='reject',
            field=models.BooleanField(default='False'),
        ),
    ]
