# Generated by Django 4.1.5 on 2023-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employees_confirm_employees_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='okay',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='employees',
            name='sendmail',
            field=models.BooleanField(default='False'),
        ),
    ]
