# Generated by Django 4.1.5 on 2023-03-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='img')),
                ('address', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
            ],
        ),
    ]
