# Generated by Django 4.1.5 on 2023-03-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='place',
        ),
    ]
